name: deployment-pipeline
on:
  push:
    branches:
      - master
jobs:
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      - name: Get repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run tests
        uses: npm run test
      - name: Compile project
        uses: npm run build
      - name: Start project 
        uses: npm run start